### ISSUE TITLE
Bilder für Vorschau und Anzeige

### ISSUE THREAD

**Issue by Khaled221284** [innomotionmedia/app_waynou2#1]
Bitte die Seitenverhältnisse und Größen der Bilder definieren

Danke

**Comment by innomotionmedia** [comment]
Für die Thumbnails: 400 x 240, 72 DPI, als JPG speichern, mittlere Qualität (sollte dann etwa 0.06 mb sein)
Für die vollen bilder: 1600 x 1000, 72 DPI, als JPG, mittlere Qualität (sollte dann etwa 0.5 mb sein)
