### ISSUE TITLE
Arabische Schrift

### ISSUE THREAD

**Issue by Khaled221284** [innomotionmedia/app_waynou2#2]
Hey, Julius,
die arabische Schrift ist linksbündig und nicht wie am Anfang besprochen rechtsbündig. Dies betrifft die Überschriften und die Namen der Hauptkategorien sowie die Dropdownmenüs praktisch alles.

**Comment by innomotionmedia** [comment]
Soweit erledigt, muss geprüft werden. (Mir fehlen teilweise Texte)
