### ISSUE TITLE
Aufforderung zum Update 

### ISSUE THREAD

**Issue by Khaled221284** [innomotionmedia/app_waynou2#4]
Ich wurde gar nicht aufgefordert die App zu aktualisieren und es passierte auch nicht automatisch. Ich musste in den Appstore gehen, die App suchen und auf aktualisieren klicken. Es kann nicht so gedacht sein oder?

**Comment by innomotionmedia** [comment]
Nein, das macht dein iPhone selbständig. Aber das gilt nur, wenn du nicht die Version ausm Testflight installiert hast, sondern die aus dem Store. Ich muss hier nicht tätig werden.
